-- MySQL Script generated by MySQL Workbench
-- Wed Jan 10 13:20:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pokemon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pokemon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pokemon` DEFAULT CHARACTER SET utf8 ;
USE `pokemon` ;

-- -----------------------------------------------------
-- Table `pokemon`.`pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokemon`.`pokemon` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NULL,
  `type` ENUM("normal", "fire", "water", "grass", "electric", "ice", "fighting", "psychic", "bug", "rock", "ghost", "dragon", "dark", "steel", "fairy") NOT NULL,
  `subtype` ENUM("normal", "fire", "water", "grass", "electric", "ice", "fighting", "psychic", "bug", "rock", "ghost", "dragon", "dark", "steel", "fairy") NULL,
  `region` ENUM("kanto", "johto", "hoenn", "sinnoh", "teselia", "kalos", "alola", "galar", "paldea") NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `pokemon`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokemon`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
